'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { run: runVendorSync } = require('../scripts/sync-browser-vendors.js');

const ROOT = path.join(__dirname, '..');
const SYNC_SCRIPT = 'scripts/sync-browser-vendors.js';
const OBSOLETE_ASSET = 'public/vendor/marked.esm.min.js';

const VENDORS = [
  {
    displayName: 'Marked',
    packageName: 'marked',
    version: '15.0.12',
    repository: 'https://github.com/markedjs/marked',
    release: 'v15.0.12',
    sourceAsset: 'node_modules/marked/lib/marked.esm.js',
    publicAsset: 'public/vendor/marked.es.js',
    sourceLicense: 'node_modules/marked/LICENSE.md',
    publicLicense: 'public/vendor/licenses/Marked-MIT.txt',
    license: 'MIT',
  },
  {
    displayName: 'DOMPurify',
    packageName: 'dompurify',
    version: '3.4.13',
    repository: 'https://github.com/cure53/DOMPurify',
    release: '3.4.13 (signed tag commit 3067f77)',
    sourceAsset: 'node_modules/dompurify/dist/purify.es.mjs',
    publicAsset: 'public/vendor/dompurify.es.js',
    sourceLicense: 'node_modules/dompurify/LICENSE',
    publicLicense: 'public/vendor/licenses/DOMPurify-Apache-2.0.txt',
    license: 'Apache-2.0',
  },
];

function absolute(relativePath) {
  return path.join(ROOT, relativePath);
}

function readRequired(relativePath, description) {
  const target = absolute(relativePath);
  assert.ok(
    fs.existsSync(target),
    `${description} is missing at ${relativePath}; run node ${SYNC_SCRIPT} --write`,
  );
  return fs.readFileSync(target);
}

function sha256(bytes) {
  return crypto.createHash('sha256').update(bytes).digest('hex');
}

function renderExpectedNotice(records) {
  const blocks = records.map(({ vendor, assetHash, licenseHash }) =>
    [
      vendor.displayName,
      `Package: ${vendor.packageName}@${vendor.version}`,
      `Repository: ${vendor.repository}`,
      `Release: ${vendor.release}`,
      `Source artifact: ${vendor.sourceAsset}`,
      `Public asset: ${vendor.publicAsset}`,
      `SHA-256: ${assetHash}`,
      'Parity: byte-identical',
      `License: ${vendor.license}`,
      `License source: ${vendor.sourceLicense}`,
      `License copy: ${vendor.publicLicense}`,
      `License SHA-256: ${licenseHash}`,
    ].join('\n'),
  );

  return [
    'Browser Vendor Provenance',
    'Generated by scripts/sync-browser-vendors.js --write.',
    'Owner: specs/003-blog-markdown-safety/contracts/vendor-integrity.md',
    'Update: node scripts/sync-browser-vendors.js --write',
    'Verify: node scripts/sync-browser-vendors.js --check',
    '',
    ...blocks.flatMap((block, index) => (index === 0 ? [block] : ['', block])),
    '',
  ].join('\n');
}

function vendorTreeSnapshot() {
  const root = absolute('public/vendor');
  if (!fs.existsSync(root)) return [];

  const entries = [];
  const visit = (directory) => {
    for (const name of fs.readdirSync(directory).sort()) {
      const target = path.join(directory, name);
      const stat = fs.statSync(target);
      if (stat.isDirectory()) {
        visit(target);
        continue;
      }
      entries.push([path.relative(root, target), sha256(fs.readFileSync(target))]);
    }
  };
  visit(root);
  return entries;
}

function writeFixtureFile(root, relativePath, bytes) {
  const target = path.join(root, relativePath);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, bytes);
}

function runFixtureSync(root) {
  let stdout = '';
  try {
    const { run } = require(path.join(root, SYNC_SCRIPT));
    run(['--write'], (message) => {
      stdout += message;
    });
    return { status: 0, stdout, stderr: '' };
  } catch (error) {
    return {
      status: 1,
      stdout,
      stderr: `Browser vendor sync failed: ${error.message}\n`,
    };
  }
}

function createSyntheticVendorRepo() {
  const holder = fs.mkdtempSync(path.join(os.tmpdir(), 'ortbtools-vendor-paths-'));
  const root = path.join(holder, 'repo');
  fs.mkdirSync(path.join(root, 'scripts'), { recursive: true });
  fs.copyFileSync(absolute(SYNC_SCRIPT), path.join(root, SYNC_SCRIPT));

  writeFixtureFile(
    root,
    'package.json',
    JSON.stringify({
      devDependencies: {
        dompurify: '3.4.13',
        marked: '15.0.12',
      },
    }),
  );
  writeFixtureFile(
    root,
    'package-lock.json',
    JSON.stringify({
      packages: {
        '': {
          devDependencies: {
            dompurify: '3.4.13',
            marked: '15.0.12',
          },
        },
        'node_modules/dompurify': {
          version: '3.4.13',
          dev: true,
          resolved: 'https://registry.npmjs.org/dompurify/-/dompurify-3.4.13.tgz',
          integrity: 'sha512-synthetic-dompurify',
        },
        'node_modules/marked': {
          version: '15.0.12',
          dev: true,
          resolved: 'https://registry.npmjs.org/marked/-/marked-15.0.12.tgz',
          integrity: 'sha512-synthetic-marked',
        },
      },
    }),
  );
  writeFixtureFile(
    root,
    'node_modules/marked/package.json',
    JSON.stringify({ version: '15.0.12' }),
  );
  writeFixtureFile(root, 'node_modules/marked/lib/marked.esm.js', 'marked-v1\n');
  writeFixtureFile(root, 'node_modules/marked/LICENSE.md', 'marked-license-v1\n');
  writeFixtureFile(
    root,
    'node_modules/dompurify/package.json',
    JSON.stringify({ version: '3.4.13' }),
  );
  writeFixtureFile(root, 'node_modules/dompurify/dist/purify.es.mjs', 'dompurify-v1\n');
  writeFixtureFile(root, 'node_modules/dompurify/LICENSE', 'dompurify-license-v1\n');

  const initial = runFixtureSync(root);
  assert.equal(initial.status, 0, initial.stderr);
  return { holder, root };
}

function changeSyntheticSources(root) {
  writeFixtureFile(root, 'node_modules/marked/lib/marked.esm.js', 'marked-v2\n');
  writeFixtureFile(root, 'node_modules/marked/LICENSE.md', 'marked-license-v2\n');
  writeFixtureFile(root, 'node_modules/dompurify/dist/purify.es.mjs', 'dompurify-v2\n');
  writeFixtureFile(root, 'node_modules/dompurify/LICENSE', 'dompurify-license-v2\n');
}

function assertRejectedWithoutMutation(result, root, expectedLicenseRoot) {
  assert.notEqual(result.status, 0, 'write mode must reject an unsafe destination ancestor');
  assert.match(
    [result.stderr, result.error?.message].filter(Boolean).join('\n'),
    /refusing unsafe browser vendor path/,
  );
  assert.equal(
    fs.readFileSync(path.join(root, 'public/vendor/marked.es.js'), 'utf8'),
    'marked-v1\n',
  );
  assert.equal(
    fs.readFileSync(path.join(expectedLicenseRoot, 'Marked-MIT.txt'), 'utf8'),
    'marked-license-v1\n',
  );
  assert.equal(
    fs.readFileSync(path.join(root, OBSOLETE_ASSET), 'utf8'),
    'obsolete-sentinel\n',
    'preflight must happen before obsolete-asset deletion',
  );
}

test('checked-in browser vendors exactly match package, lock, license, notice, and formatter ownership', () => {
  const manifest = JSON.parse(
    readRequired('package.json', 'root package manifest').toString('utf8'),
  );
  const lock = JSON.parse(readRequired('package-lock.json', 'root package lock').toString('utf8'));
  const records = [];

  for (const vendor of VENDORS) {
    assert.equal(
      manifest.devDependencies?.[vendor.packageName],
      vendor.version,
      `${vendor.packageName} must be an exact root development dependency`,
    );
    assert.equal(
      lock.packages?.['']?.devDependencies?.[vendor.packageName],
      vendor.version,
      `${vendor.packageName} root lock metadata must use the exact reviewed version`,
    );

    const lockEntry = lock.packages?.[`node_modules/${vendor.packageName}`];
    assert.ok(lockEntry, `package-lock.json is missing node_modules/${vendor.packageName}`);
    assert.equal(lockEntry.version, vendor.version, `${vendor.packageName} lock version drifted`);
    assert.equal(lockEntry.dev, true, `${vendor.packageName} must remain development-only`);
    assert.match(lockEntry.resolved || '', /^https:\/\/registry\.npmjs\.org\//);
    assert.match(lockEntry.integrity || '', /^sha512-/);

    const sourceAsset = readRequired(vendor.sourceAsset, `${vendor.displayName} package asset`);
    const publicAsset = readRequired(vendor.publicAsset, `${vendor.displayName} public asset`);
    assert.equal(
      Buffer.compare(publicAsset, sourceAsset),
      0,
      `${vendor.publicAsset} must be byte-identical to ${vendor.sourceAsset}`,
    );

    const sourceLicense = readRequired(
      vendor.sourceLicense,
      `${vendor.displayName} package license`,
    );
    const publicLicense = readRequired(
      vendor.publicLicense,
      `${vendor.displayName} copied license`,
    );
    assert.equal(
      Buffer.compare(publicLicense, sourceLicense),
      0,
      `${vendor.publicLicense} must be byte-identical to ${vendor.sourceLicense}`,
    );

    records.push({
      vendor,
      assetHash: sha256(sourceAsset),
      licenseHash: sha256(sourceLicense),
    });
  }

  const notice = readRequired('public/vendor/NOTICE.txt', 'browser vendor notice').toString('utf8');
  assert.equal(notice, renderExpectedNotice(records), 'browser vendor notice metadata drifted');
  assert.equal(
    fs.existsSync(absolute(OBSOLETE_ASSET)),
    false,
    `${OBSOLETE_ASSET} must not remain beside the reviewed Marked asset`,
  );

  const prettierLines = fs
    .readFileSync(absolute('.prettierignore'), 'utf8')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.startsWith('public/vendor/'));
  assert.deepEqual(
    prettierLines,
    VENDORS.map((vendor) => vendor.publicAsset).sort(),
    '.prettierignore must exclude exactly the two byte-owned browser modules',
  );

  const before = vendorTreeSnapshot();
  let checkOutput = '';
  runVendorSync(['--check'], (message) => {
    checkOutput += message;
  });
  assert.match(checkOutput, /Browser vendor assets are synchronized\./);
  assert.deepEqual(vendorTreeSnapshot(), before, '--check must not modify public/vendor');

  for (const invalidArgs of [[], ['--write', '--check'], ['--unknown']]) {
    assert.throws(
      () => runVendorSync(invalidArgs, () => {}),
      /usage: node scripts\/sync-browser-vendors\.js --check\|--write/,
      `arguments ${JSON.stringify(invalidArgs)} must be rejected`,
    );
  }
});

test('vendor writes preflight every destination ancestor before writing or deleting', async (t) => {
  for (const ancestor of ['public', 'public/vendor', 'public/vendor/licenses']) {
    await t.test(`rejects a ${ancestor} symlink that escapes the real repository`, () => {
      const { holder, root } = createSyntheticVendorRepo();
      t.after(() => fs.rmSync(holder, { recursive: true, force: true }));

      const original = path.join(root, ancestor);
      const outside = path.join(holder, 'outside', ancestor);
      fs.mkdirSync(path.dirname(outside), { recursive: true });
      fs.renameSync(original, outside);
      fs.symlinkSync(outside, original, 'dir');
      changeSyntheticSources(root);
      writeFixtureFile(root, OBSOLETE_ASSET, 'obsolete-sentinel\n');

      const result = runFixtureSync(root);
      const licenseRoot =
        ancestor === 'public/vendor/licenses' ? outside : path.join(root, 'public/vendor/licenses');
      assertRejectedWithoutMutation(result, root, licenseRoot);
    });
  }

  await t.test('rejects a non-directory ancestor before any partial write', () => {
    const { holder, root } = createSyntheticVendorRepo();
    t.after(() => fs.rmSync(holder, { recursive: true, force: true }));

    const licenses = path.join(root, 'public/vendor/licenses');
    fs.rmSync(licenses, { recursive: true });
    fs.writeFileSync(licenses, 'not-a-directory\n');
    changeSyntheticSources(root);
    writeFixtureFile(root, OBSOLETE_ASSET, 'obsolete-sentinel\n');

    const result = runFixtureSync(root);
    assert.notEqual(
      result.status,
      0,
      'write mode must reject a non-directory destination ancestor',
    );
    assert.match(
      [result.stderr, result.error?.message].filter(Boolean).join('\n'),
      /refusing unsafe browser vendor path/,
    );
    assert.equal(
      fs.readFileSync(path.join(root, 'public/vendor/marked.es.js'), 'utf8'),
      'marked-v1\n',
      'preflight must happen before an earlier artifact write',
    );
    assert.equal(
      fs.readFileSync(path.join(root, OBSOLETE_ASSET), 'utf8'),
      'obsolete-sentinel\n',
      'preflight must happen before obsolete-asset deletion',
    );
  });

  await t.test('rejects a directory at a late write target before any partial write', () => {
    const { holder, root } = createSyntheticVendorRepo();
    t.after(() => fs.rmSync(holder, { recursive: true, force: true }));

    const notice = path.join(root, 'public/vendor/NOTICE.txt');
    fs.unlinkSync(notice);
    fs.mkdirSync(notice);
    changeSyntheticSources(root);
    writeFixtureFile(root, OBSOLETE_ASSET, 'obsolete-sentinel\n');

    const result = runFixtureSync(root);
    assert.notEqual(result.status, 0, 'write mode must reject a non-file artifact target');
    assert.match(result.stderr, /refusing unsafe browser vendor path/);
    assert.equal(
      fs.readFileSync(path.join(root, 'public/vendor/marked.es.js'), 'utf8'),
      'marked-v1\n',
      'all write targets must be checked before the first artifact write',
    );
    assert.equal(
      fs.readFileSync(path.join(root, 'public/vendor/licenses/Marked-MIT.txt'), 'utf8'),
      'marked-license-v1\n',
    );
    assert.equal(fs.statSync(notice).isDirectory(), true);
    assert.equal(fs.readFileSync(path.join(root, OBSOLETE_ASSET), 'utf8'), 'obsolete-sentinel\n');
  });

  await t.test('rejects a directory at the obsolete target before writing or deleting', () => {
    const { holder, root } = createSyntheticVendorRepo();
    t.after(() => fs.rmSync(holder, { recursive: true, force: true }));

    const obsolete = path.join(root, OBSOLETE_ASSET);
    fs.mkdirSync(obsolete);
    changeSyntheticSources(root);

    const result = runFixtureSync(root);
    assert.notEqual(result.status, 0, 'write mode must reject a non-file obsolete target');
    assert.match(result.stderr, /refusing unsafe browser vendor path/);
    assert.equal(
      fs.readFileSync(path.join(root, 'public/vendor/marked.es.js'), 'utf8'),
      'marked-v1\n',
      'the obsolete target must be checked before the first artifact write',
    );
    assert.equal(
      fs.readFileSync(path.join(root, 'public/vendor/licenses/Marked-MIT.txt'), 'utf8'),
      'marked-license-v1\n',
    );
    assert.equal(fs.statSync(obsolete).isDirectory(), true, 'delete target must remain untouched');
  });
});
